Hide inactive associations from normal users
Inter-Actief/alexia pull request #95
Opened 2022-01-10 21:22 UTC by bramvandartel

Fixes #78.

Only superusers and foundation managers will be able to see inactive users. Furthermore, weekly reminder emails will never be sent to inactive associations.

2022-06-20 09:40 UTC, WKobes commented
@bramvandartel please resolve comments or close PR

2022-06-20 11:44 UTC, bramvandartel commented
Which comment? The pipeline is dead so no pass on testing :(

2022-07-06 11:31 UTC, WKobes requested changes
Now I see the comments were never placed, but still in draft. my mistake

2022-07-23 14:55 UTC, WKobes commented on alexia/apps/organization/managers.py
> +            return self.all()
newline

2022-07-23 14:57 UTC, WKobes commented on alexia/apps/scheduling/management/commands/remindermail.py
>          for mailtemplate in MailTemplate.objects.filter(name=MailTemplate.REMINDER, is_active=True):
better, but is it not possible to move the active check to this for loop? `organization__is_active=True` or smth?

2022-07-23 15:11 UTC, WKobes approved these changes

2022-07-23 15:11 UTC, WKobes commented
Feel free to merge, good work

2022-07-25 19:02 UTC, merged